FROM docker.uclv.cu/node:16.3.0-alpine3.11

WORKDIR /usr/src/app

COPY ./ ./

RUN export HTTP_PROXY="http://192.168.49.1:8282" \
    && export http_proxy="http://192.168.49.1:8282" \
    https_proxy="http://192.168.49.1:8282" \
    && yarn config set httpProxy http://192.168.49.1:8282 \
    && yarn config set httpsProxy http://192.168.49.1:8282 \
    && yarn install \
    && unset HTTP_PROXY http_proxy https_proxy

CMD "yarn start"